### ISSUE TITLE
About the Wt in TMI 

### ISSUE THREAD

**Issue by DavidYanAnDe** [choH/lottery_regulated_grouped_kernel_pruning#1]
Very good work, but I wonder if the Wt you used when calculating the TMI score of filter refers to the weight of the dense network after a complete training period of t, and then calculate the weight difference between it and k. Is there any problem with my understanding?

**Comment by henryzhongsc** [comment]
Thank you for your nice words :)

It looks like you have the right understanding; but to be sure, I'll reiterate the scoring mechanism here so you can double-check: the TMI score (eq. 1) is calculated element-wise between the trained model (W_t) and the same model at training epoch k (W_k) according to their *magnitude increase*, then relaxed to a structured level.
